TASK_NAME: "test_random_seed"
RNG_SEED: -1
#TEST_END_TIME: 1581541450
TEST_END_TIME: 1581541270
GROUND_TRUTH_DIR: "/home/users/qinru/codebase/ros_workspace/src/vision_semantic_segmentation/external_data/ground_truth/"
MAPPING:
  #  BOUNDARY: [[0, 600], [0, 1400]]
  BOUNDARY: [[0, 300], [0, 1000]]
  RESOLUTION: 0.2
  PCD:
    USE_INTENSITY: False
    RANGE_MAX: 20.0
  CONFUSION_MTX:
    LOAD_PATH: "/home/users/qinru/codebase/ros_workspace/src/vision_semantic_segmentation/external_data/confusion_matrix/run_trad_cnn/cfn_mtx.npy"
VISION_SEM_SEG:
  IMAGE_SCALE: 1.0
  SEM_SEG_NETWORK:
    TRAIN_DATASET: "Mapillary"
    # You may need to customize dataset configuration
    DATASET_CONFIG: "/mnt/avl_shared/qinru/iros2020/resnext50_os8/config.json"
    MODEL:
      TYPE: "DeepLabv3+"
      BACKBONE: "resnext50_32x4d"
      SYNC_BN: False
      OUTPUT_STRIDE: 8
      # You may want to use your own weight
      WEIGHT: "/mnt/avl_shared/qinru/iros2020/resnext50_os8/run1/model_best.pth"
    DATASET:
      NAME: "AVL"
      IN_CHANNELS: 3
      # Make sure the num of class is equal to the config file
      NUM_CLASSES: 19
      ROOT_DIR: "ignored"
